### ISSUE TITLE
Handling Buffer type--in Prisma

### ISSUE THREAD

**Issue by chandantiwari1** [Technoculture/VVplus#21]
Prisma doesn't support any Buffer or Blob database types at the moment. Support for them will come in the future via https://github.com/prisma/prisma/issues/446

You might be able to use String type for this(bytes @db.binary(16) but it depends on your use case.

for more details visit- [here](https://github.com/prisma/prisma/discussions/2118)

**Comment by sutyum** [comment]
fixed by #26
